version : "3"
services:
 application:
  image: registry.gitlab.com/bapth_dej/projets7:latest
  volumes:
   - /home/docker/files:/DATA/FILES
  environment:
   REPERTOIRE_PRINCIPAL: "/DATA/FILES/"
   JDBC_HOST: database
   JDBC_PORT: 3306
   JDBC_NAME: tb2g
   JDBC_USER: root
   JDBC_PASSWORD: 
  ports:
   - "8888:8080"
 database:
  image: mariadb:latest
  environment:
   MYSQL_ROOT_PASSWORD: 
   MYSQL_DATABASE: tb2g
   MYSQL_USER: root
   MYSQL_PASSWORD: 
  volumes:
   - ./docker/bdd:/docker-entrypoint-initdb.d
