version: '3.0'
services:
app:
 depends_on:
  - database
 image: wordpress:latest
 ports:
  - "8000:80"
 environment:
  WORDPRESS_DB_HOST: database:3306
  WORDPRESS_DB_USER: wordpress
  WORDPRESS_DB_PASSWORD: wordpress
database:
 image: mariadb:latest
 environment:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: wordpress
  MYSQL_USER: wordpress
  MYSQL_PASSWORD: wordpress